name: Append JSONL from PR comment
on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write

jobs:
  append:
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/append-jsonl ') && github.actor == 'jsh349'
    runs-on: ubuntu-latest
    steps:
      - name: Get PR head
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const {owner, repo} = context.repo;
            const pr = await github.rest.pulls.get({owner, repo, pull_number: context.issue.number});
            core.setOutput('ref', pr.data.head.ref);
            core.setOutput('repo', pr.data.head.repo.full_name);
            core.setOutput('isFork', pr.data.head.repo.full_name !== `${owner}/${repo}`);

      - name: Stop on fork
        if: steps.pr.outputs.isFork == 'true'
        run: echo "Fork PR not allowed" && exit 1

      - name: Checkout PR head
        uses: actions/checkout@v4
        with:
          repository: ${{ steps.pr.outputs.repo }}
          ref: ${{ steps.pr.outputs.ref }}

      - name: Extract JSON line
        run: |
          body="${{ github.event.comment.body }}"
          echo "${body#'/append-jsonl '}" > /tmp/line.json

      - name: Validate JSON and append
        run: |
          sudo apt-get update -y && sudo apt-get install -y jq
          jq -e . /tmp/line.json > /dev/null
          mkdir -p results
          if [ -s results/results.jsonl ]; then printf "\n" >> results/results.jsonl; fi
          cat /tmp/line.json >> results/results.jsonl

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add results/results.jsonl
          git commit -m "append-jsonl by ${{ github.actor }}"
          git push
