name: Append JSONL from PR comment
on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write

jobs:
  append:
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/append-jsonl ') && github.actor == 'jsh349'
    runs-on: ubuntu-latest
    steps:
      - name: Get PR head
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const {owner, repo} = context.repo;
            const pr = await github.rest.pulls.get({owner, repo, pull_number: context.issue.number});
            core.setOutput('ref', pr.data.head.ref);
            core.setOutput('full', pr.data.head.repo.full_name);
            core.setOutput('isFork', pr.data.head.repo.full_name !== `${owner}/${repo}`);

      - name: Guard: same-repo only
        if: steps.pr.outputs.isFork == 'true'
        run: echo "Fork PR not allowed" && exit 1

      - name: Checkout PR head
        uses: actions/checkout@v4
        with:
          repository: ${{ steps.pr.outputs.full }}
          ref: ${{ steps.pr.outputs.ref }}

      - name: Append one JSON object (no jq)
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const body = context.payload.comment.body;
            const prefix = '/append-jsonl ';
            const line = body.startsWith(prefix) ? body.slice(prefix.length) : '';
            if (!line || line.includes('\n')) throw new Error('JSON must be single-line');
            let obj; try { obj = JSON.parse(line); } catch(e){ throw new Error('Invalid JSON'); }
            if (typeof obj !== 'object' || Array.isArray(obj)) throw new Error('Top-level must be object');
            fs.mkdirSync('results', { recursive: true });
            const p = 'results/results.jsonl';
            const needsNL = fs.existsSync(p) && fs.statSync(p).size > 0;
            fs.appendFileSync(p, (needsNL? '\n' : '') + line, {encoding:'utf8'});

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add results/results.jsonl
          git commit -m "append-jsonl by ${{ github.actor }}"
          git push
