name: Append JSONL from PR comment
on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write

jobs:
  append:
    # PR의 댓글이고, '/append-jsonl '로 시작하며, 댓글 작성자가 본인일 때만
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/append-jsonl ') && github.actor == 'jsh349' }}
    runs-on: ubuntu-latest
    steps:
      - name: Get PR head info
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner, repo: context.repo.repo,
              pull_number: context.issue.number
            });
            core.setOutput('headRef', pr.data.head.ref);
            core.setOutput('repo', pr.data.head.repo.full_name);

      - name: Checkout PR head
        uses: actions/checkout@v4
        with:
          repository: ${{ steps.pr.outputs.repo }}
          ref: ${{ steps.pr.outputs.headRef }}

      - name: Parse & validate JSON (single-line)
        run: |
          set -euo pipefail
          body="${{ github.event.comment.body }}"
          line="${body#'/append-jsonl '}"
          printf "%s" "$line" > /tmp/line.json
          python - <<'PY'
import json, pathlib, sys
s = pathlib.Path('/tmp/line.json').read_text().strip()
assert '\n' not in s, "single-line JSON only"
json.loads(s)  # validate
PY

      - name: Append to results/results.jsonl
        run: |
          mkdir -p results
          if [ -f results/results.jsonl ] && [ -s results/results.jsonl ]; then printf "\n" >> results/results.jsonl; fi
          cat /tmp/line.json >> results/results.jsonl

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add results/results.jsonl
          git commit -m "append-jsonl by ${{ github.actor }}"
          git push
