name: Grok reply and append JSONL
on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write

jobs:
  grok:
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/grok ') && github.actor == 'jsh349'
    runs-on: ubuntu-latest
    steps:
      - name: Get PR head
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const {owner, repo} = context.repo;
            const pr = await github.rest.pulls.get({owner, repo, pull_number: context.issue.number});
            core.setOutput('ref', pr.data.head.ref);
            core.setOutput('repo', pr.data.head.repo.full_name);

      - name: Checkout PR head
        uses: actions/checkout@v4
        with:
          repository: ${{ steps.pr.outputs.repo }}
          ref: ${{ steps.pr.outputs.ref }}

      - name: Extract prompt
        run: |
          body="${{ github.event.comment.body }}"
          echo "${body#'/grok '}" > /tmp/prompt.txt

      - name: Call xAI Chat Completions
        env:
          XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
        run: |
          sudo apt-get update -y && sudo apt-get install -y jq
          PROMPT=$(cat /tmp/prompt.txt)
          curl -sS https://api.x.ai/v1/chat/completions \
            -H "Authorization: Bearer ${XAI_API_KEY}" \
            -H "Content-Type: application/json" \
            -d "$(jq -n --arg p "$PROMPT" '{model:"grok-3-mini",messages:[{"role":"system","content":"Reply briefly for a GitHub log."},{"role":"user","content":$p}] }')" \
            | tee /tmp/out.json
          TEXT=$(jq -r '.choices[0].message.content' /tmp/out.json)
          mkdir -p results
          jq -cn --arg msg "$TEXT" '{model:"grok4",role:"theory",version:"TGT-U v1.1",env:"handshake",seed:0,kpi:{message:$msg},invariance:{}}' > /tmp/line.json
          if [ -s results/results.jsonl ]; then printf "\n" >> results/results.jsonl; fi
          cat /tmp/line.json >> results/results.jsonl

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add results/results.jsonl
          git commit -m "grok: append reply by ${{ github.actor }}"
          git push
